services:
  database:
    container_name: ds-mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    attach: false

  redis:
    container_name: ds-redis
    ports:
      - "6379:6379"
    image: redis:latest
