services:
  app:
    container_name: ds-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
    environment:
      - MONGODB_URL=mongodb://database:27017/
    depends_on:
      - database
    restart: unless-stopped

  database:
    container_name: ds-mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
