name: Tests on push
on:
  push:
    branches:
    - master 
  pull_request:
    branches:
    - master 

jobs:
  run_tests:
   runs-on: ubuntu
   container:
     image: catthehacker/ubuntu:act-latest
   steps:
     # Чекаут кода.
     - name: Checkout code 
       uses: actions/checkout@master

     # Установка python 3.11.
     - name: Python setup 
       uses: actions/setup-python@v4
       with:
        python-version: "3.11"
     
     - name: Docker setup
       uses: docker/setup-buildx-action@v3

     # Настройка окружения.
     - name: Env setup
       run: |
        docker compose up -d
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="/root/.local/bin:$PATH"
        poetry install --with test
        poetry add -D pytest-cov
        poetry run pytest --cov=. --cov-report=xml --cov-report=term
        


      